apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: argocd
spec:
  type: ClusterIP  
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
