apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP  # For internal access (use LoadBalancer/NodePort for external)
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
